### ISSUE TITLE
Bug creating events on September 2019

### ISSUE THREAD

**Issue by Escarribur** [intljusticemission/react-big-calendar#1271] opened 2019-03-28 20:57 UTC
#### Do you want to request a _feature_ or report a _bug_?
Report a bug
#### What's the current behavior?
I want to create an event in September 2019, the event is created but is not displayed on the calendar.

The issue is replicable on the demo.
http://recordit.co/tQGl3FPAfF
![Screen Shot 2019-03-28 at 5 55 48 PM](https://user-images.githubusercontent.com/7866584/55192254-c8532000-5182-11e9-9271-a4dc58e0a48a.png)

This only happen only in the first column of September, tested with 2019 and 2020.
I changed the order of the days leaving Monday as the first column of the calendar and the same thing happens.

#### What's the expected behavior?
That the event is visible in these days of September.

**Comment by arecvlohe** [comment] 2019-05-06 19:36
@Escarribur I am not able to reproduce. This is what I have:

<a href="https://cl.ly/2e0c3e7b482b" target="_blank"><img src="https://d3r69eeiwn2k86.cloudfront.net/items/1E070J3Y0T2j0d3I4123/Screen%20Shot%202019-05-06%20at%203.34.21%20PM.png" style="display: block;height: auto;width: 100%;"/></a>

<a href="https://cl.ly/2e0c3e7b482b" target="_blank"><img src="https://d3r69eeiwn2k86.cloudfront.net/items/1E070J3Y0T2j0d3I4123/Screen%20Shot%202019-05-06%20at%203.34.21%20PM.png" style="display: block;height: auto;width: 100%;"/></a>

Must be a weird bug in your browser. Closing for now.

**Closed by arecvlohe** 2019-05-06 19:36 UTC
