### ISSUE TITLE
Timezone support

### ISSUE THREAD

**Issue by dgouldin** [intljusticemission/react-big-calendar#118] opened 2016-06-11 03:35 UTC
It would be nice if there was a way to display a calendar in a timezone other than the browser's local one. `moment-timezone` supports timezone conversion using a named zone:

http://momentjs.com/timezone/docs/#/using-timezones/converting-to-zone/

I attempted to make this work by setting moment's default timezone, but it looks like all of the date "math" to determine the range of days and weeks is done by `date-arithmetic`, a library that AFAICT has no awareness of timezones.

**Comment by jquense** [comment] 2016-06-11 11:39
times ones should just be a matter of what dates you provide, the date math shouldn't need to know what tz you want to work... what bits aren't working?

**Comment by dgouldin** [comment] 2016-06-12 02:25
`Date` always assumes the browser's timezone. So when you take an ISO 8601 datetime string like `'2016-01-01T00:00:00Z'` and convert it to a `Date` using moment, the object you get back is no longer in the timezone originally specified. (In my case, the example string becomes `Thu Dec 31 2015 16:00:00 GMT-0800 (PST)`.)

So now `react-big-calendar` is taking those UTC datetimes which javascript converted to PST and doing math like "start of day", which gives the correct answer in PST but the wrong answer in UTC.

As I said earlier, I can get halfway there by telling moment to always convert to a given timezone. That causes the times events to show up in the correct timezone, but because the time column start and end dates are computed using `date-arithmetic`, the column doesn't render as midnight to midnight. (In the case where my events are in UTC and my local computer is PST, it renders 4pm to 4pm.)

I think you're assuming that you can just entirely ignore the timezone and treat all datetimes as timezone-naive, but in reality, there is no such thing as a timezone-naive datetime in javascript. I'd much rather be able to explicitly state the timezone I'd like the calendar to render in than try to manually convert to local time as if the event was already in the local timezone.

**Comment by cgc** [comment] 2016-06-13 23:53
Given that fullcalendar actually [explicitly deals in terms of ambiguous time](http://fullcalendar.io/docs/utilities/Moment/#ambiguously-timed), there seems to be precedent for the difficulty of integrating it explicitly into the core.

I can imagine ways to integrate it as a plugin, or at least with minimal footprint in the calendar core by doing something like wrapping `props.events` and wrapping the various callback functions to do conversion to and from zoned/zoneless.

a sketch of what the wrapper might look like:
```javascript
const ZonedCalendar = React.createClass({
  onSelectSlot(slotInfo) {
    return this.props.onSelectSlot({
      start: forceZone(slotInfo.start, this.props.timezone),
      end: forceZone(slotInfo.end, this.props.timezone),
    });
  },
  onSelectEvent(event) {
    return this.props.onSelectEvent(event._originalEvent);
  },
  render() {
    const events = this.props.events.map(event =>
      toAmbiguousEvent(event, this.props.timezone));
    return <BigCalendar
      { ...this.props }
      onSelectSlot={ this.onSelectSlot }
      onSelectEvent={ this.onSelectEvent }
      events={ events }
    />;
  },
});


function toAmbiguousEvent(event, tz) {
  return {
    ...event,
    start: toAmbiguousDate(event.start, tz),
    end: toAmbiguousDate(event.end, tz),
    // Thinking a scheme like this is best: it means that the event object you
    // put in the event object you get out, making equality comparison later
    // on easier.
    _originalEvent: event,
  };
}

function toAmbiguousDate(dt, tz) {
  // just wrote this one, so it's a bit of a guess

  // the sign of getTimezoneOffset is opposite of moment
  const browserOffset = -1 * new Date().getTimezoneOffset();
  const result = moment(dt).tz(tz);
  // adding moment's offsets takes you back to UTC, so we add the utcOffset
  // of the input and subtract the offset of the browser to render the time
  // for the browser.
  result.add(result.utcOffset() - browserOffset, 'minutes');
  return result.toDate();
}

function forceZone(dt, tz) {
  // pulled this from our fullcalendar integration
  const result = moment(dt).tz(tz);
  result.add(result.utcOffset(), 'minutes');
  return result;
}
```

**Comment by s-taylor** [comment] 2016-06-22 02:21
I haven't looked at what methods BigCalendar uses internally from the localiser, but I was thinking it might work if you could bind moment with the timezone. Something like...

```
const _ = require('lodash');
const moment = require('moment-timezone');

const momentBound = _.partial(moment.tz, _, <timezone-here>)
```
Then pass momentBound in as the big calendar moment localizer. I'm also trying to solve this issue at the moment and going to see if this might work...

**Comment by jquense** [comment] 2016-06-22 03:07
we are explicitly deferring to date libraries like moment to handle this sort of thing via localizers. I haven't delta with TZ issues myself but I'd be interested to know where we aren't being ambiguous about it. I'm guessing  that's mostly a matter of date math creating date objects

**Comment by s-taylor** [comment] 2016-06-22 05:01
Let me articulate the problem a bit better. When Big Calendar renders dates it is displaying these on the calendar using your browser's timezone (which comes from their device configuration whatever that may be). If you change your timezone setting the dates in Big Calendar will move to reflect that change.

This is what I don't want to happen, I want to render dates in the calendar in a specific timezone irrespective of the users browser's timezone. The reason for this, is the particular project I'm working on, the users will have a timezone associated with their profile. When then see dates in the calendar they want it to be based on this defined timezone. This is relevant because if they take a trip overseas and their device timezone changes they don't want the dates in the calendar to change as they haven't changed their timezone preference. Does that make sense?

I've managed to hack around this by applying an offset to the start / end date of each event that is the delta between their timezone preference and the browser's timezone.

**Comment by dgouldin** [comment] 2016-06-22 05:26
I've implemented a similar workaround which I'd prefer not to have to do. In my component that wraps Big Calendar, I have a couple of methods:

```
toLocalTimezone(dateStr) {
  // Construct a local timezone date string ignoring the source timezone
  const dateStrNoTz = moment(dateStr).tz(this.state.timezone).format('YYYY-MM-DDTHH:mm:ss');
  return moment(dateStrNoTz).format();
},

toTargetTimezone(dateStr) {
  // Construct a target timezone date string ignoring the source timezone
  const dateStrNoTz = moment(dateStr).format('YYYY-MM-DDTHH:mm:ss');
  return moment.tz(dateStrNoTz, this.state.timezone).format();
},
```

Dates that come out of BigCalendar (like the one passed to `onNavigate`) go through `toTargetTimezone` before being sent to the back end, and dates that come from the back end go through `toLocalTimezone` before being passed to Big Calendar.

**Comment by jquense** [comment] 2016-06-22 12:42
I understand the issue y'all, I just don't know why and how RBC would be to blame.  it defers _all_ rendering of dates to the localizer. What I'd like to happen is that you just configure Moment or Globalize to handle timezones and it should work, and RBC just renders whatever you give it. 

the only place I think this might break is where RBC creates dates but I think those places are fairly limited and in most cases it could use the offset of the dates it already has. if someone wants to dig more into it I'm sure I'd accept a PR

**Comment by dgouldin** [comment] 2016-06-22 15:30
Ah ok, yes my main concern is the dependency on `date-arithmetic`. It's the only bit that can't be made timezone aware without modifying the dependency itself.

**Comment by jquense** [comment] 2016-06-22 15:41
@dgouldin I don't think it needs to be timezone aware though. all the dates should be the same TZ and it should maintain them during any Math yeah? It may need to be adjusted to do that though, thats fine as well (I own that dep anyway)

**Comment by dgouldin** [comment] 2016-06-22 15:44
The problem is as soon as you start working with native `Date` objects, everything is in the browser's timezone, so in order to accomplish "all dates should be in the same TZ", you'll need to actually have support for dates that aren't in the browser's timezone.

**Comment by jquense** [comment] 2016-06-22 15:47
That is only true if you don't specify an offset, we can have any date math maintain the input date's offset fairly straight forwardly I think

**Comment by wendykwok** [comment] 2016-10-21 06:11
wanna circle back to this issue, I am trying to set default timezone in moment but it doesn't seem like BigCalendar honoring the moment.defaultZone value and probably I did something obviously wrong here.

Fwiw, when I set the system timezone to Asia/Tokyo which works like a charm but below code snippets simply doesn't work. any thoughts?

```
moment.tz.setDefault("Asia/Tokyo");
BigCalendar.setLocalizer(
  BigCalendar.momentLocalizer(moment)
);
```

**Comment by fxfactorial** [comment] 2017-01-21 10:18
@wendykwok I'm using it this way: 

```javascript
import moment_timezone from 'moment-timezone';
moment_timezone.tz.setDefault('Asia/Yerevan');

BigCalendar.momentLocalizer(moment_timezone);
```

And that works correctly for me.

**Comment by pencilcheck** [comment] 2017-02-22 22:32
Tried both solutions from @wendykwok and @fxfactorial however none of them worked. BigCalendar still displays the event in user local timezone instead of the timezone specified in moment-timezone using setDefault

**Comment by pencilcheck** [comment] 2017-02-23 03:20
I have a workaround by setting the date components manually into the Javascript Date()

startdate is the moment date object of the event in the target timezone.
event.startdate is the date object passed into Big Calendar

```javascript
event.startdate = new Date(startdate.year(), startdate.month(), startdate.date(), startdate.hour(), startdate.minute(), 0);
event.enddate = new Date(enddate.year(), enddate.month(), enddate.date(), enddate.hour(), enddate.minute(), 0);
```

**Comment by jasonogasian** [comment] 2017-03-10 06:18
I am using the moment-timezone setDefault method posted by @fxfactorial and it is working for setting the time bar but not the correct day in week or month view. Creating a new moment() object does create with the correct date, not sure why the calendar isn't using it.

**Comment by rafinskipg** [comment] 2017-03-21 12:44
@pencilcheck I would love to see a more detailed explanation about that because I don't understand how the calendar picks startdate instead of start/end on the events.

**Comment by jtomaszewski** [comment] 2017-03-27 21:58
@pencilcheck workaround works for me. Just not sure if it works correctly with the DST changes and so on, because it's a "fake move": we are changing the date's timezone. While 2:30am might exist in startdate's timezone, it may not exist in `event.startdate`'s timezone (browser's timezone). Not sure what happens then

**Comment by jtomaszewski** [comment] 2017-03-27 22:17
Nah, there's something we'll have to fix in ReactBigCalendar I think.

Example: My local browser's timezone is Europe/Warsaw . We have DST change on 26th march at 2am. I entered 4 events:

- 25.03 2am
- 26.03 1am
- 26.03 2am
- 26.03 3am

When passing `events` prop to BigCalendar, I'm bassing native `new Date()` object, which return those values:

- Sat Mar 25 2017 02:00:00 GMT+0100 (CET)
- Sun Mar 26 2017 01:00:00 GMT+0100 (CET)
- Sun Mar 26 2017 03:00:00 GMT+0200 (CEST)
- Sun Mar 26 2017 04:00:00 GMT+0200 (CEST)

(so times are given in a correct timezone)

However, this is how ReactBigCalendar renders it:

![image](https://cloud.githubusercontent.com/assets/1862580/24380491/e960d958-134b-11e7-943f-0b8fb037509c.png)


Any ideas how to tackle it? ;)

**Comment by jtomaszewski** [comment] 2017-03-29 23:05
Another problem appeared for me, when I started to use `moment.tz.setDefault()`... which switches the default zone created by `moment()` calls. In my project I can have actually 3 different timezones at use:

- BigCalendar's timezone - this I want to set with a `timeZoneName` prop
- current user's timezone - this is currently set with `moment.tz.setDefault`
- current user browser's (local) timezone - this we cannot change

Of course I could just not use moment.tz.setDefault(), but I like it cuz its handy. 

So here's my working crossplatform hack in case anybody would need:

1. Big Calendar setup

```
// remember the browser's local timezone, as it might by used later on
BigCalendar.tz = moment.tz.guess()
// format all dates in BigCalendar as they would be rendered in browser's local timezone (even if later on they won't)
const m = (...args) => moment.tz(...args, BigCalendar.tz)
m.localeData = moment.localeData

BigCalendar.setLocalizer(
  BigCalendar.momentLocalizer(m)
)
```

BigCalendar component wrapper:

```
const convertDateTimeStringToDate = (datetime, timeZoneName) => {
  const m = moment.tz(datetime, timeZoneName)
  return new Date(m.year(), m.month(), m.date(), m.hour(), m.minute(), 0)
}

const convertDateToDateTimeString = (date, timeZoneName) => {
  const dateM = moment.tz(date, BigCalendar.tz)
  const m = moment.tz({
    year: dateM.year(),
    month: dateM.month(),
    date: dateM.date(),
    hour: dateM.hour(),
    minute: dateM.minute(),
  }, BigCalendar.tz)
  return m
}

const TimeZoneAgnosticBigCalendar = ({ events, onSelectSlot, onEventDrop, timeZoneName, ...props }) => {
  const bigCalendarProps = {
      ...props,
      events: events.map(event => ({
        ...event,
        start: convertDateTimeStringToDate(event.start, timeZoneName),
        end: convertDateTimeStringToDate(event.end, timeZoneName),
      })),
      onSelectSlot: onSelectSlot && (({ start, end, slots }) => {
        onSelectSlot({
          start: convertDateToDateTimeString(start, timeZoneName),
          end: convertDateToDateTimeString(end, timeZoneName),
          slots: slots.map(date => convertDateToDateTimeString(date, timeZoneName)),
        })
      }),
      onEventDrop: onEventDrop && (({ event, start, end }) => {
        onEventDrop({
          event,
          start: convertDateToDateTimeString(start, timeZoneName),
          end: convertDateToDateTimeString(end, timeZoneName),
        })
      }),
  }
  return <BigCalendar {...bigCalendarProps} />
}
```

**Comment by IanLondon** [comment] 2017-04-26 16:21
This may be too obvious to be helpful, but if you have times as datetime strings with a UTC offset, eg "2017-04-26T11:55:54-04:00", they will render in the local time (eg "11:55:54 am") when formatted with Moment.js.

**Comment by peterox** [comment] 2017-05-17 00:53
@jtomaszewski you are a legend. Your piece of magic worked for me.

I made a few modifications to make use of the startAccessor and endAccessor instead of mapping all events
```javascript
import React, {Component} from 'react'
import PropTypes from 'prop-types'
import BigCalendar from 'react-big-calendar'
import {accessor} from 'react-big-calendar/lib/utils/accessors'
import moment from 'moment'
import 'moment-timezone'

import 'react-big-calendar/lib/css/react-big-calendar.css';

// remember the browser's local timezone, as it might by used later on
BigCalendar.tz = moment.tz.guess();
// format all dates in BigCalendar as they would be rendered in browser's local timezone (even if later on they won't)
const m = (...args) => moment.tz(...args, BigCalendar.tz);
m.localeData = moment.localeData;

BigCalendar.setLocalizer(
  BigCalendar.momentLocalizer(m)
);



export const convertDateTimeToDate = (datetime, timeZoneName) => {
  const m = moment.tz(datetime, timeZoneName);
  return new Date(m.year(), m.month(), m.date(), m.hour(), m.minute(), 0)
};

export const convertDateToDateTime = (date, timeZoneName) => {
  const dateM = moment.tz(date, BigCalendar.tz);
  return moment.tz({
    year: dateM.year(),
    month: dateM.month(),
    date: dateM.date(),
    hour: dateM.hour(),
    minute: dateM.minute(),
  }, BigCalendar.tz);
};


class TimeZoneAgnosticBigCalendar extends Component {
  static propTypes = {
    events: PropTypes.array,
    onSelectSlot: PropTypes.func,
    onEventDrop: PropTypes.func,
    timeZoneName: PropTypes.string,
    startAccessor: PropTypes.func,
    endAccessor: PropTypes.func,
  };

  static defaultProps = {
    startAccessor: 'start',
    endAccessor:'end'
  };

  startAccessor = (event) => {
    const start = accessor(event, this.props.startAccessor);
    return convertDateTimeToDate(start, this.props.timeZoneName);
  };

  endAccessor = (event) => {
    const end = accessor(event, this.props.endAccessor);
    return convertDateTimeToDate(end, this.props.timeZoneName);
  };

  render() {
    const { onSelectSlot, onEventDrop, timeZoneName, ...props } = this.props;
    const bigCalendarProps = {
      ...props,
      startAccessor: this.startAccessor,
      endAccessor: this.endAccessor,
      onSelectSlot: onSelectSlot && (({start, end, slots}) => {
        onSelectSlot({
          start: convertDateToDateTime(start, timeZoneName),
          end: convertDateToDateTime(end, timeZoneName),
          slots: slots.map(date => convertDateToDateTime(date, timeZoneName)),
        })
      }),
      onEventDrop: onEventDrop && (({event, start, end}) => {
        onEventDrop({
          event,
          start: convertDateToDateTime(start, timeZoneName),
          end: convertDateToDateTime(end, timeZoneName),
        })
      }),
    };
    return <BigCalendar {...bigCalendarProps} />
  }
}
export default TimeZoneAgnosticBigCalendar;
```

**Comment by dedan** [comment] 2017-07-22 08:15
@peterox @jtomaszewski Thank you two very much for your code, that saved me a few hours. However I'm a bit confused about `convertDateToDateTime` where you pass in `timeZoneName` but then use the browser's time that you'd stored in `BigCalendar.tz`. 

Am I missing something here or is that a bug?

**Comment by jtomaszewski** [comment] 2017-07-27 07:06
Oh, true. AFAIK everything works okay with this code. So, that `timeZoneName` argument in `convertDateToDateTime` is just needless.

**Comment by ramkandasamy** [comment] 2017-08-01 18:29
So I'm using react-big-calendar version 0.14.4, and for me, the simple solution worked, i.e.:

`
import moment from 'moment';
import moment_timezone from 'moment-timezone';
moment.tz.setDefault("UTC");
BigCalendar.momentLocalizer(moment);`

Just throwing that out there for any new users of this library.

**Comment by ndevvy** [comment] 2017-10-31 22:06
I am trying to address the issue raised in @ramkandasamy edit - when I pass a localizer with a different time zone to BigCalendar, the events display correctly, but the Day and Week views still show the hours of the day (and organize events into day columns) based on my browser local time.

**Comment by fbatista** [comment] 2017-11-03 15:45
using the tweaks suggested by @peterox and @jtomaszewski with a user-defined timezone different than the browser's almost works, but the current time indicator on the day and week views shows in the "wrong" place.

Imho, the only way to actually solve this issue without hacking is to use moment for calculations instead of date-arithmetic, as the current .startOf(date,'day') and endOf(date,'day') functions used by the date-arithmetic  don't take into account a desired timezone, resulting in 0:00 of browser timezone, that as others have mentioned will result in the times being rendered very weirdly.

**Comment by snozal** [comment] 2017-11-15 14:06
I am having the same issue as @fbatista, can this be prioritized?

**Comment by jquense** [comment] 2017-11-15 14:38
I'm not likely to tackle this any time soon. If folks are looking for a fix i'd be happy to take a lost cost fix in date-arithmetic to use a specified offset for calculations. I'm not looking for fixes tho that strip it out and replace it with moment :)

**Comment by ml653** [comment] 2017-11-28 07:25
Same issue as the one @fbatista and @ndevvy pointed out above.

**Comment by ndevvy** [comment] 2017-11-28 07:52
@jquense - would you be open to fixes that add the ability to set custom functions for utils/dates.js?

**Comment by jquense** [comment] 2017-11-28 12:54
I don't think so. These utils are deep and integral to the component working in big and extremely subtle ways. Even slight behavior differences in custom functions could break many expectations the rest of the code base has. I much prefer we add proper support vs adding hooks for people to hack fixes in

**Comment by pencilcheck** [comment] 2017-11-30 03:05
one of the moment maintainer published a new time library now that suppose to support timezone out of the box!

https://moment.github.io/luxon/

**Comment by bradleyy1012** [comment] 2017-12-09 22:21
@pencilcheck how does this help with changing the timezone for the calendar events? initially i thought it was a way to set the browsers timezone but apparently not :(

**Comment by pencilcheck** [comment] 2017-12-10 08:18
@bradleyy1012 because moment doesn't support timezone at all. It does everything in local time and automatically assumes local time in whatever time you put in. moment-timezone supports timezone but it doesn't have a good API to back up so it is equally confusing might as well not using it.

I see luxon is trying to solve that and having a library that is clear on what it is assuming helps a ton when you are dealing with time that are in different timezone and want to convert between them.

**Comment by bradleyy1012** [comment] 2017-12-10 09:56
@pencilcheck ah i see. what i ended up doing was, since i keep all datetimes on the server in utc time, i just converted it to the timezone i wanted on the server, sent it back as a timestamp string, then parsed the string for the year, month, day, hour, minute and did `start: new Date(year, month - 1, day, hour, minute);` do you think theres anything that could go wrong with this method?

**Comment by pencilcheck** [comment] 2017-12-12 00:30
@bradleyy1012 new Date() automatically converts into local time from the time you give, and since you store the time in UTC, that is going to mess everything up.

moment() uses new Date() constructor and it has the same issue. You want  a library that actually takes the time in UTC and convert properly into the target timezone you wanted...

**Comment by jedwards1211** [comment] 2017-12-14 21:48
As anyone who has to work with remote timezones knows, the lack of remote timezone support in moment and JS Dates was a huge mistake.  Luxon made it right.

**Comment by tobiasandersen** [comment] 2018-02-06 23:15
Reading through this it seems like all problems could be solved by the suggestions above from @peterox and @jtomaszewski, except for positioning the current time indicator correctly — but that should now be possible since https://github.com/intljusticemission/react-big-calendar/pull/707 by @ehahn9. So I guess it can finally be closed(?) Please re-open if this is not the case! 

If anyone's up for it, creating an example for all this would be awesome!

**Comment by ndevvy** [comment] 2018-02-06 23:42
I have not yet tried implementing a custom `nowAccessor` as enabled by #707, but I believe the issues with displaying events in the wrong day when attempting to use remote timezones will persist as long as date-arithmetic functions that use `new Date()` are used, e.g., `startOf` and `endOf` in `Week.range`.

**Comment by tobiasandersen** [comment] 2018-02-06 23:47
Reading through it again, I think you're right @ndevvy. Sorry about that!

**Comment by larkintuckerllc** [comment] 2018-02-23 03:54
The goal is to show events and the current day / time using a different (than local) timezone.

Tried the recommendation of initializing moment's timezone, e.g, `moment.tz.setDefault('Japan')`. This did end up formatting the events correctly for the timezone but screwed with the minimum and maximum times it shows on the week and day grid (wanted to keep 12:00).  So, I left the timezone alone and adjusted the event times to make them show up correctly.

```
const s = moment(startTS).tz(tz);
const e = moment(endTS).tz(tz);
// CREATE FAKE TIME IN LOCAL TIMEZONE
const newStart = new Date(s.year(), s.month(), s.date(), s.hour(), s.minute(), s.second());
const newEnd = new Date(e.year(), e.month(), e.date(), e.hour(), e.minute(), e.second());
```

Then used a similar trick using the new `nowAccessor` feature (property is actually called `getNow`) to change the date / time of the current time.

```
const n = moment.tz(new Date(), tz); // CREATE NOW IN TZ
// GENERATE A FAKE TIME IN LOCAL TIMEZONE
const getNow = () => new Date(n.year(), n.month(), n.date(), n.hour(), n.minute(), n.second());
BigCalendar.momentLocalizer(moment);
const MyCalendar = props => (
  <BigCalendar
    events={events}
    getNow={getNow}
    defaultDate={getNow()}
  />
);
```
The only remaining issue is that the green bar (and bold text) showing the current time on the current day does not work if the current day of the fake time does not match the actual current day (in local timezone). Something that I can live with.

**Comment by jedwards1211** [comment] 2018-02-23 17:36
Honestly I think most people here will have more luck using another lib to convert dates from a remote timezone to the same calendar time in the local timezone before passing them into BigCalendar... That's what I've done in one of my apps.

**Comment by ehahn9** [comment] 2018-02-23 17:43
If anyone would like a PR, I have a higher order component `withTimeZone` which wraps the calendar with functions to convert zoned times to local times and vis-versa in all the right places (`startAccessor`, `endAccessor`, `getNow` all of the event handlers etc.). Our app is multi-timezone, so we had to build the HOC for this... If there's support, I could move it from our project into the `/addons` of r-b-c?

**Comment by ndevvy** [comment] 2018-02-23 19:10
@larkintuckerllc - does your solution allow events to be displayed on the correct day when they land on different days in the local timezone vs. the remote timezone?

**Comment by abelosorio** [comment] 2018-06-14 19:40
Need a solution for this... This behavior makes RBC to lose all its charming.

I'm facing a problem similar to Taylor's (https://github.com/intljusticemission/react-big-calendar/issues/118#issuecomment-227644225). I have to show entries in a user-defined timezone.

I can't continue using this package if this issue is not resolved. It's a shame. It looks nice.

This issue has been discussed for more than 2 years now...

**Comment by jquense** [comment] 2018-06-14 20:09
> Need a solution for this...

"Physician heal thyself" 👍

**Comment by abelosorio** [comment] 2018-06-14 20:13
Where is your open source mind? You're denying an issue just for pride.

Sorry man, but if you continue in this path, this project is going to know what `>/dev/null` means... such a shame....

**Comment by jquense** [comment] 2018-06-14 20:19
excuse me we accept PR's, you are grumpy because someone here is not scratching your itch for you. If you want to talk about the "open source mind" stop complaining about how people aren't doing something for you in the spare time fast enough for your liking, and jump in and help instead. No one here is gonna feel bad because you are unhappy with the free work of others.

**Comment by abelosorio** [comment] 2018-06-14 20:28
This would be already fixed if you had accepted doing date calculations with moment instead of date-arithmetic...

**Comment by jquense** [comment] 2018-06-14 20:36
there are plenty of reasons to not use Moment, biggest of which it would severely limit the who and and how many folks can you use it (Such as #816 for example). So no. that's not a valid fix.

Folks, showing up to an OSS project complaining about how features aren't being added to your standards while also not doing anything to help is a "Bad Look". You are never going to look like the hero making demands on people who building things in their spare time and offering them for free to whoever wants to use them.

I do not even use this project regularly anymore but still spend a fair amount of time maintaining it, fixing bugs, and helping folks get their PR's merged. Don't show up here talking about how i'm being selfish, and expect a beneficial outcome.

**Comment by abelosorio** [comment] 2018-06-14 20:44
Time to say goodbye... :-1:

**Comment by jquense** [comment] 2018-06-14 20:44
👋

**Comment by GavinThomas1192** [comment] 2018-06-15 17:51
I think there a tons, including myself and close developers that would love to contribute, especially for different localizers!

**Comment by GavinThomas1192** [comment] 2018-06-15 20:33
@jedwards1211 I believe that's what my group is going to try and do with luxon! I'm sure they will contact @jquense if successful.

**Comment by jquense** [comment] 2018-06-15 20:34
My hope is that, yes this could be handled by a localizer. It seems like at a minimum tho we need to add some hook to date-math, so it can construct or maintain the correct offset. Ideally it should be similar to how date-math and the localizers interact with regard to first day of the week

**Comment by GavinThomas1192** [comment] 2018-06-15 20:40
I got close, the calendar is rendering with most relevant data but it is in fact first day of week that is the problem. See here https://github.com/moment/luxon/issues/114#issuecomment-397367798

**Comment by jquense** [comment] 2018-06-15 21:16
@GavinThomas1192 if you can't get it from underlying library the best option is probably for the localizer is to have the user pass it in :/ maybe you can supliment with cldr data for your supported cultures

```
setLocalizer(luxonLocalizer({ firstDayOfWeek: 1 })
```

**Comment by jedwards1211** [comment] 2018-06-15 21:57
@jquense It should suffice to have a function that takes a date, determines the desired display calendar time, and returns a date with the same calendar time in the local timezone right?

(Plus a function that does the reverse)

**Comment by jedwards1211** [comment] 2018-06-15 22:02
@abelosorio as someone who used to love moment like you do, I want to point out that it actually isn't very good at handling remote timezones.  I actually switched an entire webapp from moment to luxon because we needed to deal with remote timezones.

**Comment by ehahn9** [comment] 2018-06-16 00:07
Hi all. Maybe this would help? I've been using it successfully with RBC for some time. It seems like this sort of thing might make a nice addon?

https://gist.github.com/ehahn9/704bf086c058c74e3a5a43067d053089

**Comment by navneetccna** [comment] 2018-06-20 09:22
I tried all solutions but no success

My System timezone is Asia/Calcutta and profile is US/Eastern no calendar showing current date is 19 but actual date is 20. what is the solution for this problem.

**Comment by arecvlohe** [comment] 2018-06-20 22:48
@ehahn9 I would be interested to see that as an addon. Submit a PR and let's hash it out.

**Comment by ehahn9** [comment] 2018-06-25 16:55
I hope to get to this but it might be a few weeks :-( -- I think the major work item is simply to move this into addons and create a storybook or two... I have some rebasing to do to catch up to the master tho -- no hard feelings if someone else takes this over the finish line!

**Comment by khoaanh2212** [comment] 2018-08-13 08:10
i have the same problem like @navneetccna .every timezone of profile later than system timezone will return calendar in month later than 1 day.with the early timezone.show right

**Comment by alansutherland** [comment] 2018-10-11 00:56
> I think after so many suggestions made by many people. They described specific problems and have proposed solutions. You could add the fix. In this way your project would improve for others. But in the comments you can only see that you are not interested in improving. Sad.

I agree, this is apparent across all discussions on this repo @jquense you always seem disinterested in helping others use something you created and surely understand better than anyone else. I guess you just can't be bothered but when you create a repo that becomes popular and is used by thousands of devs you need to take ownership of it.

**Comment by dlerman2** [comment] 2019-01-04 16:04
@ehahn9 Thanks for that gist - very helpful! Are the referenced files available somewhere -- /client/utils/timezones, /client/utils/date?

**Comment by jquense** [comment] 2019-01-04 16:19
@nileshtrivedi There isn't a specific plan, I've outlined above a few steps I think are probably required to support TZ's, and others have contributed as well, nothing is probably sufficient tho, just first steps. If you wanna jump in we are happy to support, tho admittedly it's not an issue i've a lot of familiarity in doing correctly. 

In terms of constraints tho:
- don't require timezone data in core to support (in localizers is fine)
- don't use one specific localization library, it needs to work generally with moment, luxon, etc. 
- it's fine if TZ support only works for localization libraries that can handle it, e.g. maybe luxon can't but moment can
- We should try and keep an solution minimal in terms of complexity in core and byte size

**Comment by rufoot** [comment] 2019-04-11 20:49
@jquense 
I am going to convert UTC date to CDT timezone date. How can I integrate it?

**Comment by diegoarcega** [comment] 2019-05-20 20:51
I'm having the same problem @khoaanh2212 plus:


**Errors**
* Day starts at 9:00 PM instead of 12:00 AM
* Today is 20th and it shows 19th

** I'm using moment-timezone

![image](https://user-images.githubusercontent.com/1951007/58051107-b27d2e00-7b27-11e9-84db-91d9aa1f5cd5.png)

**Comment by wootwoot1234** [comment] 2019-06-27 19:10
@dlerman2 did you end up figuring out what the /client/utils/timezones, /client/utils/date files are?  Did you find a solution to this?

**Comment by wootwoot1234** [comment] 2019-06-27 19:15
@ehahn9 Thanks for that gist - very helpful! Are the referenced files available somewhere -- /client/utils/timezones, /client/utils/date?

**Comment by User1m** [comment] 2019-07-27 03:22
@jtomaszewski helped solve our problem. Use his wrapper.
https://github.com/intljusticemission/react-big-calendar/issues/118#issuecomment-290253011

**Comment by davidroman0O** [comment] 2019-10-07 20:45
First, thank you @dgouldin 

Then, don't forget to add : 

```javascript
 slotPropGetter: slotPropGetter && ((date) => {
                return slotPropGetter(
                   convertDateToDateTime(date, timeZoneName)
                )
            }),
```

On my case, I want to manipulate the dates more easily in full ISO. 

Thx for the lib and this extended timezone support ! 😄

**Closed** 2019-12-20 21:38 UTC
Labels: enhancement, feature request, help wanted, wontfix

**Comment by hamez0r** [comment] 2020-01-08 19:42
> @jtomaszewski helped solve our problem. Use his wrapper.
> [#118 (comment)](https://github.com/intljusticemission/react-big-calendar/issues/118#issuecomment-290253011)

What's the version this patch works on?

**Comment by krvajal** [comment] 2020-03-06 11:55
@diegoarcega I am having the same issue as you. The problem is that the call to
https://github.com/jquense/react-big-calendar/blob/master/src/Day.js#L22
returns the start of day in the current timezone instead of the timezone the calendar is in.

https://github.com/jquense/date-math

**Comment by itsalb3rt** [comment] 2022-03-15 14:07
> @wendykwok I'm using it this way:
> 
> ```js
> import moment_timezone from 'moment-timezone';
> moment_timezone.tz.setDefault('Asia/Yerevan');
> 
> BigCalendar.momentLocalizer(moment_timezone);
> ```
> 
> And that works correctly for me.

This still working! It is a very nice approach to set the timezone!

**Comment by mjieyoub** [comment] 2023-07-11 20:05
For those using `date-fns`, this is a solution that I'm using to offset by the difference between browser time zone and desired displayed time zone.

```
import { differenceInHours, addHours } from "date-fns"
import { zonedTimeToUtc } from "date-fns-tz"
import { Event } from "react-big-calendar"

const mapEvents = (events: any[]): Event[] =>
    events.map(event => {
        const [start, end] = getDatesWithOffset(
            event.start,
            event.end,
            event.timeZone
        )

        return {
            ...event,
            start,
            end,
        }
    })

const getDatesWithOffset = (
    startTime: Date | number,
    endTime: Date | number,
    timeZone: string
): [Date, Date] => {
    // Get the time zoned check in
    const zonedStart = zonedTimeToUtc(startTime, timeZone)

    // Calculate the offset (moving in opposite direction of the delta)
    const offset = differenceInHours(zonedStart, startTime) * -1

    // Adjust check in and check out by the offset
    const startWithOffset = addHours(startTime, offset)
    const endWithOffset = addHours(endTime, offset)

    return [startWithOffset, endWithOffset]
}
```

and then in your calendar component:
```
<BigCalendar
     {...}
     events={mapEvents(events)}
/>
```

**Comment by XpTo2k** [comment] 2023-10-27 15:40
I had this issue and solved it with the following code (start and end):

`new Date(someUtcDate.replace("Z", ""))`

**Comment by cutterbl** [comment] 2023-10-30 12:45
When needing timezone specific implementations, I would use either the moment or luxon localizers. We have examples for this in our documentation.

**Comment by sayinmehmet47** [comment] 2024-05-26 08:41
@itsalb3rt  using your approach works in slots placement correctly, but for max and min date of the calendar change anyhow. My calendar change min date change from `00:00` to min date when i change the timezone. and also drag and drop does not place the slots correctly
