### ISSUE TITLE
Setting defaultView/view to "week" sets day view with an empty heading

### ISSUE THREAD

**Issue by 555ea** [intljusticemission/react-big-calendar#278] opened 2017-01-20 10:48 UTC
Hi, not sure whether it's for me, but v0.12.1-v0.12.3 have this bug. I've seen that you have no issues with the demo, but for me i have to force a `setTimeout(()=> this.setState({view:'week'}))` in order to change view at init.

My code looks like:

```
import React, {Component} from 'react';
import 'react-big-calendar/lib/css/react-big-calendar.css';
import BigCalendar from 'react-big-calendar';
import moment from 'moment';
import './MyCalendar.scss';

BigCalendar.setLocalizer(
    BigCalendar.momentLocalizer(moment)
);

class MyCalendar extends Component {
    state = {view: 'week'}

   // componentDidMount(){
   //     setTimeout(()=> this.setState({view:'week'}))
   // }

    render(){
        let today = moment();
        let am8 = today.set('hour', 8).set('minutes', 0).toDate();
        let pm8 = today.set('hour', 21).set('minutes', 0).toDate();

        return (
            <div>
                <BigCalendar
                    events={[]}
                    min={am8}
                    max={pm8}
                    views={['month', 'week', 'day']}
                    view={this.state.view}
                    formats={{timeGutterFormat: 'h A', dayFormat:'ddd D'}}
                    step={30}
                    onView={(view)=>{
                        this.setState({view})
                    }}
                />
            </div>
        );
    }
}

export default MyCalendar
```
![screenshot_267](https://cloud.githubusercontent.com/assets/13518952/22146962/3c5390c2-df0f-11e6-889a-0852dd66a900.png)

**Comment by tobiasandersen** [comment] 2017-01-20 11:50
Hi! From the docs on the `view` prop:

> controlled by: onView, initialized with: defaultView

Try adding `defaultView='week'` as a prop to the calendar.

**Comment by 555ea** [comment] 2017-01-20 12:22
Same result, as mentioned in issue's heading setting neither `"defaultView={"week"}"` nor `"view={'this.state.view'} onView={(view)=>this.setState({view})}"` is not helping, they both result in a broken "day" view. I've even tried `"defaultView={'week'} view={'this.state.view'} onView={(view)=>this.setState({view})}"`.

Is there anything else i could try ?

**Comment by tobiasandersen** [comment] 2017-01-20 12:34
Sorry, I must have missed reading the title. If that doesn't work I don't know what the problem is. I think both should work. @jquense How do you handle the `defaultView` prop? I can't seem to find it in the source. 

@555ea I'm unable to reproduce this, can you point to a repo showing it?

**Comment by 555ea** [comment] 2017-01-20 13:17
@tobiasandersen here you are, the bug is reproduced here
https://github.com/555ea/react-big-calendar-view-week-bug

**Comment by tobiasandersen** [comment] 2017-01-20 13:54
Oh I see, thanks for the link. I actually think this is a duplicate of https://github.com/intljusticemission/react-big-calendar/issues/128.

**Comment by 555ea** [comment] 2017-01-20 14:25
Is there any solution other than setTimeout ? It's pretty critical

**Comment by jquense** [comment] 2017-01-20 14:52
i'll take a look at your repo. up until this point we haven't had anything reproducing the bug so no workarounds.

**Comment by jquense** [comment] 2017-01-20 15:11
too a quick look. It's clear that the component is getting rendered before the css for the component has loaded which is messing up the gutter width calculation (its measuring the unstyled content). This is more an issue with how webpack imports css without extract css.

The immediate workaround is to load the css in a `<link>` tag in the head instead of importing it with style-loader

**Closed** 2017-07-07 13:29 UTC

**Comment by VincentRichard555** [comment] 2018-02-24 20:26
I also encountered this (with other libraries as well) when trying to render before my data pull from a db is completed. Waiting until the data is actually pulled to render fixes this for react-big-calendar as well as other libraries.
