### ISSUE TITLE
Next/Prev give "Invalid Date"

### ISSUE THREAD

**Issue by npalansky** [intljusticemission/react-big-calendar#768] opened 2018-03-19 16:28 UTC
#### Do you want to request a _feature_ or report a _bug_?
report a bug

#### What's the current behavior?
Clicking the next / prev button results in an "Invalid Date".  
Clicking on the today button before clicking next/prev fixes this 

Note: this bug only occurs in v0.18

**Comment by arecvlohe** [comment] 2018-03-19 17:15
Duplicate of #718 I believe.

**Comment by arecvlohe** [comment] 2018-04-20 16:03
Looks like there is a workaround for this at the moment. I am going to close.

**Closed by arecvlohe** 2018-04-20 16:03 UTC
Labels: bug
