### ISSUE TITLE
🎉🎉 Rearrange algorithm 🚑🚑

### ISSUE THREAD

**Issue by ckcks12** [intljusticemission/react-big-calendar#1464] opened 2019-09-24 02:51 UTC
#### Do you want to request a _feature_ or report a _bug_?

I want to request a feature. It's related to arrangement of events.

#### What's the current behavior?

![image](https://user-images.githubusercontent.com/12825679/65958181-c64b8000-e489-11e9-9246-bd351ae5c9bb.png)

Now, in this calendar, if there are more than two events having same start time, one of them **cover the other events** and I think it could be imporved by writing **new rearrange algorithm**.

#### What's the expected behavior?

![image](https://user-images.githubusercontent.com/12825679/65958425-51c51100-e48a-11e9-9c6c-a92118706b22.png)

It is expected to work as just like Toast UI Calendar.

Furthermore I'd like to to be a contributor for this awesome project. So if you don't mind can I make pull request for this feature? If so, I'm gonna optimize it and also write some explanation too!

Thank you.

=====

See how my algorithm handles plenty of events.

![](https://miro.medium.com/max/1633/1*w3nD80V2C9B6odJmm-Gnnw.png)

**Comment by dmitrykrylov** [comment] 2019-09-30 09:44
@ckcks12 I already created a pull request with similar updates on algorithm. It seems that maintainers didn't treat my proposal as a good solution and haven't approved it.
https://github.com/intljusticemission/react-big-calendar/pull/1405

Please create your pull request and maybe your changes will be merged. I am really interested in solving arrangement issues.

**Comment by KhaledMohamedP** [comment] 2019-09-30 14:21
@dmitrykrylov  & @ckcks12,

Does your solutions cover stacked events? ref: #1440

**Comment by ckcks12** [comment] 2019-10-01 02:29
@KhaledMohamedP  Yeah of course :) haha

![image](https://user-images.githubusercontent.com/12825679/65929803-5f54a980-e43e-11e9-8d04-77b0a65e531a.png)

![image](https://user-images.githubusercontent.com/12825679/65929765-45b36200-e43e-11e9-99f0-a5d4a744a8f0.png)
![image](https://user-images.githubusercontent.com/12825679/65929779-519f2400-e43e-11e9-832f-d64443215fdd.png)


above one is from 01:00 ~ 01:40 and the other one is from 01:40 ~ 02:10.

So, it worths $100 ? haha :laughing: :lol:

**Comment by ckcks12** [comment] 2019-10-01 02:46
@KhaledMohamedP 
You expect that those events are connected seamlessly? without the 2% padding between them?
I think the padding is not bad actually. The real problem is that they are not arranged properly in horizontal way.

![image](https://user-images.githubusercontent.com/12825679/65929803-5f54a980-e43e-11e9-8d04-77b0a65e531a.png)
![image](https://user-images.githubusercontent.com/12825679/65929765-45b36200-e43e-11e9-99f0-a5d4a744a8f0.png)
![image](https://user-images.githubusercontent.com/12825679/65929779-519f2400-e43e-11e9-832f-d64443215fdd.png)

Here's my solution. Mine is also trying to put padding between them. We can find this behavior in Google Calendar.

![image](https://user-images.githubusercontent.com/12825679/65930530-0b978f80-e441-11e9-8fd1-83925f1d0ac6.png)

**Comment by ckcks12** [comment] 2019-10-01 05:18
@KhaledMohamedP Btw, I just tested it now (with the version v0.22.1) and it works below.

![image](https://user-images.githubusercontent.com/12825679/65935997-fa0cb280-e455-11e9-9d67-3b3643f55774.png)

Is it what you want?

**Comment by KhaledMohamedP** [comment] 2019-10-01 08:27
@ckcks12 the issue is not with 30mins appointments, its usually with events shorter than 30 minutes (e.g. 20mins). You will need to change the slot selection to the following

```
 step={10}
 timeslots={6}
```

then, you will have to create a set of 20 minutes events in the same hour!

**Comment by jquense** [comment] 2019-10-01 12:18
@ckcks12 I'd love to see what you came up with. In general we'd really like the arranging algorithm to be pluggable so folks can customize it, but i know that's not super easy to add. Overall We are open to new ways of doing stuff, but there should be good case for why the solution is better *generally* for people, as a library we need to meet the needs of many different use cases!

Please do feel free to open up a PR with what you've got!

**Comment by KhaledMohamedP** [comment] 2019-10-02 13:18
@ckcks12 your solution provides a better alignment algorithm for events around the same time 👏 

It also addresses this issue I reported a month ago #1440 

Good job!

**Comment by Canuckaholic** [comment] 2019-10-07 23:49
My team is also currently facing issues around event arrangement and would love to see this merged! Cheers.

**Comment by jbwestphal** [comment] 2019-10-08 17:33
It would be nice having this merged, pls!

**Comment by Canuckaholic** [comment] 2019-10-09 05:42
Hey @jquense... love the plug-in, and totally understand if you're too busy to address this PR at the moment. Really appreciate all the effort that's been put into making this one of the best React calendars out there. But... can you let us know if there's no immediate plans to merge this PR or address the arrangement, as we'll need to explore other options for the project that my team is working on. We have a situation where there are quite a few overlapping events, and we just can't use the arrangement out of the box (attaching what it looks like). Thanks again for this library.
![image](https://user-images.githubusercontent.com/945663/66454460-ccf36d80-ea1c-11e9-9e7a-efc4f9897446.png)

**Closed** 2019-10-18 04:32 UTC
