### ISSUE TITLE
Back and Next buttons crash calendar

### ISSUE THREAD

**Issue by berryman17** [intljusticemission/react-big-calendar#722] opened 2018-02-11 23:57 UTC
I am able to view the calendar and use the week, day, etc views. My issue arises when I click the Next or Back buttons in Month view. I receive this errors: 
```
Month.js:217 Uncaught TypeError: Cannot read property '0' of undefined
    at MonthView.renderHeaders (Month.js:217)
    at MonthView.render (Month.js:209)
    at finishClassComponent (react-dom.development.js:10249)
    at updateClassComponent (react-dom.development.js:10226)
    at beginWork (react-dom.development.js:10605)
    at performUnitOfWork (react-dom.development.js:12573)
    at workLoop (react-dom.development.js:12682)
    at HTMLUnknownElement.callCallback (react-dom.development.js:1299)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:1338)
    at invokeGuardedCallback (react-dom.development.js:1195)
    at performWork (react-dom.development.js:12800)
    at batchedUpdates (react-dom.development.js:13244)
    at performFiberBatchedUpdates (react-dom.development.js:1646)
    at stackBatchedUpdates (react-dom.development.js:1637)
    at batchedUpdates (react-dom.development.js:1651)
    at Object.batchedUpdatesWithControlledComponents [as batchedUpdates] (react-dom.development.js:1664)
    at dispatchEvent (react-dom.development.js:1874)
```

I have found that if the Today button is pressed first, I don't have the issue. Perhaps I'm missing a step or prop. Here is my current code for the component:
```
const Calendar = props => (
  <div className="calendar-div">
    <BigCalendar
      events={props.events}
    />
  </div>
)

```
Any help is greatly appreciated.

**Comment by arecvlohe** [comment] 2018-02-12 00:08
Duplicate of #718 I believe

**Closed** 2018-03-15 13:13 UTC
